---- Set schema
--SET search_path TO meethub_schema;
--
---- Users table
--CREATE TABLE users (
--    id BIGSERIAL PRIMARY KEY,
--    email VARCHAR(255) UNIQUE NOT NULL,
--    password VARCHAR(255) NOT NULL,
--    first_name VARCHAR(100) NOT NULL,
--    last_name VARCHAR(100) NOT NULL,
--    role VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
--    phone_number VARCHAR(20),
--    enabled BOOLEAN NOT NULL DEFAULT TRUE,
--    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
--    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
--    account_locked_until TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- User preferences table
--CREATE TABLE user_preferences (
--    id BIGSERIAL PRIMARY KEY,
--    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--    preference_key VARCHAR(100) NOT NULL,
--    preference_value VARCHAR(500),
--    privacy_level VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- Locations table
--CREATE TABLE locations (
--    id BIGSERIAL PRIMARY KEY,
--    name VARCHAR(200) NOT NULL,
--    address TEXT,
--    city VARCHAR(100),
--    country VARCHAR(100),
--    latitude NUMERIC(10, 6),
--    longitude NUMERIC(10, 6),
--    type VARCHAR(20) NOT NULL,
--    virtual_meeting_url VARCHAR(500),
--    access_code VARCHAR(50),
--    driving_instructions TEXT,
--    timezone VARCHAR(50)
--);
--
---- Meetings table
--CREATE TABLE meetings (
--    id BIGSERIAL PRIMARY KEY,
--    title VARCHAR(200) NOT NULL,
--    description TEXT,
--    agenda TEXT,
--    type VARCHAR(20) NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
--    visibility VARCHAR(20) NOT NULL,
--    start_date TIMESTAMP NOT NULL,
--    end_date TIMESTAMP NOT NULL,
--    max_participants INTEGER,
--    organizer_id BIGINT NOT NULL REFERENCES users(id),
--    location_id BIGINT REFERENCES locations(id),
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- Meeting tags table
--CREATE TABLE meeting_tags (
--    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
--    tag VARCHAR(100) NOT NULL,
--    PRIMARY KEY (meeting_id, tag)
--);
--
---- Meeting participants table
--CREATE TABLE meeting_participants (
--    id BIGSERIAL PRIMARY KEY,
--    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
--    user_id BIGINT NOT NULL REFERENCES users(id),
--    status VARCHAR(20) NOT NULL DEFAULT 'INVITED',
--    permission_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
--    comment TEXT,
--    invitation_token VARCHAR(100) UNIQUE,
--    token_expires_at TIMESTAMP,
--    response_date TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    UNIQUE (meeting_id, user_id)
--);
--
---- Meeting resources table
--CREATE TABLE meeting_resources (
--    id BIGSERIAL PRIMARY KEY,
--    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
--    filename VARCHAR(255) NOT NULL,
--    original_filename VARCHAR(255) NOT NULL,
--    file_path VARCHAR(500) NOT NULL,
--    file_size BIGINT,
--    mime_type VARCHAR(100),
--    resource_type VARCHAR(50) NOT NULL,
--    version INTEGER NOT NULL DEFAULT 1,
--    is_current BOOLEAN NOT NULL DEFAULT TRUE,
--    uploaded_by BIGINT REFERENCES users(id),
--    access_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANTS',
--    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- Meeting tasks table
--CREATE TABLE meeting_tasks (
--    id BIGSERIAL PRIMARY KEY,
--    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
--    title VARCHAR(200) NOT NULL,
--    description TEXT,
--    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
--    assigned_to BIGINT REFERENCES users(id),
--    due_date TIMESTAMP,
--    completed_at TIMESTAMP,
--    progress_percentage INTEGER NOT NULL DEFAULT 0,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- Notifications table
--CREATE TABLE notifications (
--    id BIGSERIAL PRIMARY KEY,
--    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--    title VARCHAR(200) NOT NULL,
--    message TEXT,
--    type VARCHAR(20) NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL',
--    reference_id BIGINT,
--    reference_type VARCHAR(50),
--    sent_at TIMESTAMP,
--    read_at TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);
--
---- Grant permissions to application user
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA meethub_schema TO meethub_user;
--GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA meethub_schema TO meethub_user;
--GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA meethub_schema TO meethub_app;
--GRANT USAGE ON ALL SEQUENCES IN SCHEMA meethub_schema TO meethub_app;