--SET search_path TO meethub_schema;
--
---- Users indexes
--CREATE INDEX idx_user_email ON users(email);
--CREATE INDEX idx_user_role ON users(role);
--CREATE INDEX idx_user_created ON users(created_at);
--
---- User preferences indexes
--CREATE INDEX idx_user_pref_user ON user_preferences(user_id);
--CREATE INDEX idx_user_pref_key ON user_preferences(preference_key);
--
---- Locations indexes
--CREATE INDEX idx_location_coordinates ON locations(latitude, longitude);
--CREATE INDEX idx_location_type ON locations(type);
--CREATE INDEX idx_location_city ON locations(city);
--
---- Meetings indexes
--CREATE INDEX idx_meeting_organizer ON meetings(organizer_id);
--CREATE INDEX idx_meeting_status ON meetings(status);
--CREATE INDEX idx_meeting_start_date ON meetings(start_date);
--CREATE INDEX idx_meeting_end_date ON meetings(end_date);
--CREATE INDEX idx_meeting_visibility ON meetings(visibility);
--CREATE INDEX idx_meeting_date_range ON meetings(start_date, end_date);
--
---- Meeting participants indexes
--CREATE INDEX idx_participant_meeting ON meeting_participants(meeting_id);
--CREATE INDEX idx_participant_user ON meeting_participants(user_id);
--CREATE INDEX idx_participant_status ON meeting_participants(status);
--
---- Meeting resources indexes
--CREATE INDEX idx_resource_meeting ON meeting_resources(meeting_id);
--CREATE INDEX idx_resource_type ON meeting_resources(resource_type);
--
---- Meeting tasks indexes
--CREATE INDEX idx_task_meeting ON meeting_tasks(meeting_id);
--CREATE INDEX idx_task_assignee ON meeting_tasks(assigned_to);
--CREATE INDEX idx_task_status ON meeting_tasks(status);
--CREATE INDEX idx_task_due_date ON meeting_tasks(due_date);
--
---- Notifications indexes
--CREATE INDEX idx_notification_user ON notifications(user_id);
--CREATE INDEX idx_notification_status ON notifications(status);
--CREATE INDEX idx_notification_created ON notifications(created_at);