#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#
#spring.jpa.properties.hibernate.default_schema=meethub_schema
#
#
#
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true




spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.default_schema=meethub_schema

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
