package com.meethub.domain.model.enums;

public enum NotificationType {
    MEETING_INVITATION,
    MEETING_REMINDER,
    MEETING_UPDATE,
    MEETING_CANCELLATION,
    PARTICIPATION_CONFIRMED,
    WAITLIST_PROMOTION,
    TASK_ASSIGNMENT,
    SYSTEM_ANNOUNCEMENT,
    SECURITY_ALERT
}