-- =============================================
-- MeetHub H2 Database Schema Script
-- For testing with Spring Boot Data JPA
-- =============================================

-- 1. CREATE SCHEMA (H2 doesn't support CREATE DATABASE in embedded mode)
CREATE SCHEMA IF NOT EXISTS meethub_schema;

-- Set schema
SET SCHEMA meethub_schema;

-- =============================================
-- 2. TABLES
-- =============================================

-- Users table - UŻYJ IDENTITY ZAMIAST AUTO_INCREMENT DLA H2
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
    phone_number VARCHAR(20),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    account_locked_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_notifications_enabled BOOLEAN DEFAULT TRUE,
    push_notifications_enabled BOOLEAN DEFAULT TRUE,
    sms_notifications_enabled BOOLEAN DEFAULT FALSE,
    digest_enabled BOOLEAN DEFAULT TRUE,
    digest_frequency VARCHAR(20) DEFAULT 'DAILY',
    timezone VARCHAR(50) DEFAULT 'Europe/Warsaw',
    language VARCHAR(10) DEFAULT 'pl'
);

-- User preferences table
CREATE TABLE IF NOT EXISTS user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    preference_key VARCHAR(100) NOT NULL,
    preference_value VARCHAR(500),
    privacy_level VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Locations table
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address TEXT,
    city VARCHAR(100),
    country VARCHAR(100),
    latitude DECIMAL(10, 6),
    longitude DECIMAL(10, 6),
    type VARCHAR(20) NOT NULL,
    virtual_meeting_url VARCHAR(500),
    access_code VARCHAR(50),
    driving_instructions TEXT,
    timezone VARCHAR(50)
);

-- Meetings table
CREATE TABLE IF NOT EXISTS meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    agenda TEXT,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    visibility VARCHAR(20) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    max_participants INTEGER,
    organizer_id BIGINT NOT NULL,
    location_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_pattern VARCHAR(100),
    recurrence_end_date TIMESTAMP,
    recurrence_exceptions VARCHAR(4000),
    is_template BOOLEAN DEFAULT FALSE,
    original_meeting_id BIGINT,
    workflow_stage VARCHAR(50) DEFAULT 'DRAFT',
    metadata VARCHAR(4000),
    FOREIGN KEY (organizer_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (original_meeting_id) REFERENCES meetings(id)
);

-- Meeting tags table
CREATE TABLE IF NOT EXISTS meeting_tags (
    meeting_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    added_by BIGINT,
    PRIMARY KEY (meeting_id, tag),
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (added_by) REFERENCES users(id)
);

-- Meeting participants table
CREATE TABLE IF NOT EXISTS meeting_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'INVITED',
    permission_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
    comment TEXT,
    invitation_token VARCHAR(100) UNIQUE,
    token_expires_at TIMESTAMP,
    response_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    join_method VARCHAR(50),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    feedback TEXT,
    attendance_duration_minutes INTEGER,
    attendance_confirmed_at TIMESTAMP,
    attendance_token_used VARCHAR(255),
    UNIQUE (meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Participant status history table
CREATE TABLE IF NOT EXISTS participant_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    old_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    comment TEXT,
    changed_by_user_id BIGINT,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (participant_id) REFERENCES meeting_participants(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);

-- Waitlist entries table
CREATE TABLE IF NOT EXISTS waitlist_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    auto_promote BOOLEAN NOT NULL DEFAULT TRUE,
    notified_at TIMESTAMP,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- User groups table
CREATE TABLE IF NOT EXISTS user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    description TEXT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- User group members table
CREATE TABLE IF NOT EXISTS user_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (group_id, user_id),
    FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Meeting resources table
CREATE TABLE IF NOT EXISTS meeting_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    resource_type VARCHAR(50) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    uploaded_by BIGINT,
    access_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANTS',
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    download_count INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

-- Resource tags table
CREATE TABLE IF NOT EXISTS resource_tags (
    resource_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (resource_id, tag),
    FOREIGN KEY (resource_id) REFERENCES meeting_resources(id) ON DELETE CASCADE
);

-- Meeting tasks table
CREATE TABLE IF NOT EXISTS meeting_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    assigned_to BIGINT,
    due_date TIMESTAMP,
    completed_at TIMESTAMP,
    progress_percentage INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(id)
);

-- Notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL',
    reference_id BIGINT,
    reference_type VARCHAR(50),
    sent_at TIMESTAMP,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    template_key VARCHAR(100),
    scheduled_for TIMESTAMP,
    delivered_at TIMESTAMP,
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Email templates table
CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key VARCHAR(100) UNIQUE NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body_template TEXT NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'pl',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(200),
    category VARCHAR(100),
    description TEXT,
    variables_help TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    version INTEGER DEFAULT 1,
    channel VARCHAR(50),
    available_variables TEXT
);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'TODO',
    deadline TIMESTAMP,
    meeting_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    allow_self_assignment BOOLEAN,
    max_file_size INTEGER,
    max_files_per_user BIGINT,
    allowed_file_types TEXT DEFAULT 'pdf,doc,docx,jpg,png',
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Task assignments table
CREATE TABLE IF NOT EXISTS task_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'ASSIGNED',
    comment TEXT,
    completed_at TIMESTAMP,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    UNIQUE(task_id, user_id),
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Task files table
CREATE TABLE IF NOT EXISTS task_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT,
    content_type VARCHAR(100),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    assignment_id BIGINT NOT NULL,
    FOREIGN KEY (assignment_id) REFERENCES task_assignments(id) ON DELETE CASCADE
);

-- Feedback table
CREATE TABLE IF NOT EXISTS feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Meeting statistics table
-- Meeting statistics table
CREATE TABLE IF NOT EXISTS meeting_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL UNIQUE,

    -- Podstawowe metryki
    total_participants INTEGER NOT NULL DEFAULT 0,
    attended_participants INTEGER NOT NULL DEFAULT 0,
    confirmed_participants INTEGER DEFAULT 0,
    declined_participants INTEGER DEFAULT 0,
    pending_participants INTEGER DEFAULT 0,

    -- Frekwencja
    attendance_rate DECIMAL(5,2),
    confirmation_rate DECIMAL(5,2),

    -- Czasy odpowiedzi
    avg_response_time_minutes DECIMAL(10,2),
    min_response_time_minutes DECIMAL(10,2),
    max_response_time_minutes DECIMAL(10,2),

    -- Czas trwania
    avg_join_delay_minutes DECIMAL(10,2),
    avg_participation_duration_minutes DECIMAL(10,2),
    total_meeting_duration_minutes INTEGER,

    -- Statystyki uczestnictwa
    max_concurrent_participants INTEGER,
    current_participants INTEGER DEFAULT 0,
    peak_participants_today INTEGER DEFAULT 0,

    -- Feedback
    average_rating DECIMAL(3,2),
    feedback_count INTEGER DEFAULT 0,
    positive_feedback_count INTEGER DEFAULT 0,
    negative_feedback_count INTEGER DEFAULT 0,

    -- Koszty
    total_cost DECIMAL(15,2),
    cost_per_participant DECIMAL(10,2),

    -- Statusy
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    is_finalized BOOLEAN NOT NULL DEFAULT FALSE,
    data_quality_score DECIMAL(3,2),

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    generated_at TIMESTAMP NOT NULL,
    last_calculated_at TIMESTAMP,
    valid_until TIMESTAMP,

    -- JSON metryki (H2 używa VARCHAR dla JSON)
    additional_metrics VARCHAR(4000),

    -- Wersja
    version INTEGER DEFAULT 0,

    -- Klucze obce
    CONSTRAINT fk_meeting_statistics_meeting
        FOREIGN KEY (meeting_id)
        REFERENCES meetings(id) ON DELETE CASCADE,

    -- Constraints
    CONSTRAINT chk_attendance_rate_range
        CHECK (attendance_rate >= 0 AND attendance_rate <= 100),
    CONSTRAINT chk_confirmation_rate_range
        CHECK (confirmation_rate >= 0 AND confirmation_rate <= 100),
    CONSTRAINT chk_average_rating_range
        CHECK (average_rating >= 0 AND average_rating <= 5)
);

-- Meeting votings table
CREATE TABLE IF NOT EXISTS meeting_votings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    max_choices INTEGER,
    allow_suggestions BOOLEAN DEFAULT FALSE,
    deadline_date TIMESTAMP,
    auto_close BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE
);

-- Voting options table
CREATE TABLE IF NOT EXISTS voting_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_id BIGINT NOT NULL,
    option_date TIMESTAMP NOT NULL,
    option_duration_minutes INTEGER,
    is_suggested BOOLEAN DEFAULT FALSE,
    suggested_by BIGINT,
    FOREIGN KEY (voting_id) REFERENCES meeting_votings(id) ON DELETE CASCADE,
    FOREIGN KEY (suggested_by) REFERENCES users(id)
);

-- Votes table
CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    vote_weight INTEGER DEFAULT 1,
    preference_order INTEGER,
    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_voting_option UNIQUE (user_id, voting_id, option_id),
    FOREIGN KEY (voting_id) REFERENCES meeting_votings(id) ON DELETE CASCADE,
    FOREIGN KEY (option_id) REFERENCES voting_options(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    color_code VARCHAR(7) DEFAULT '#3498db',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Meeting categories table
CREATE TABLE IF NOT EXISTS meeting_categories (
    meeting_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (meeting_id, category_id),
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- Meeting status changes table
CREATE TABLE IF NOT EXISTS meeting_status_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    changed_by_user_id BIGINT,
    reason VARCHAR(500),
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);

-- Attendance tokens table
CREATE TABLE IF NOT EXISTS attendance_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    meeting_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE
);

-- User notification channels table
CREATE TABLE IF NOT EXISTS user_notification_channels (
    user_id BIGINT NOT NULL,
    channel VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, channel),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Notification variables table
CREATE TABLE IF NOT EXISTS notification_variables (
    notification_id BIGINT NOT NULL,
    variable_key VARCHAR(100) NOT NULL,
    variable_value TEXT,
    PRIMARY KEY (notification_id, variable_key),
    FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE
);

-- Notification schedules table
CREATE TABLE IF NOT EXISTS notification_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    schedule_type VARCHAR(50) NOT NULL,
    trigger_time VARCHAR(20),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    custom_settings TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- 3. INDEXES (Basic indexes for H2)
-- =============================================

-- Users indexes
CREATE INDEX IF NOT EXISTS idx_user_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_user_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_user_created ON users(created_at);

-- Meetings indexes
CREATE INDEX IF NOT EXISTS idx_meeting_organizer ON meetings(organizer_id);
CREATE INDEX IF NOT EXISTS idx_meeting_status ON meetings(status);
CREATE INDEX IF NOT EXISTS idx_meeting_start_date ON meetings(start_date);
CREATE INDEX IF NOT EXISTS idx_meeting_end_date ON meetings(end_date);

-- Meeting participants indexes
CREATE INDEX IF NOT EXISTS idx_participant_meeting ON meeting_participants(meeting_id);
CREATE INDEX IF NOT EXISTS idx_participant_user ON meeting_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_participant_status ON meeting_participants(status);

-- Notifications indexes
CREATE INDEX IF NOT EXISTS idx_notification_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_status ON notifications(status);

-- Voting indexes
CREATE INDEX IF NOT EXISTS idx_voting_meeting ON meeting_votings(meeting_id);
CREATE INDEX IF NOT EXISTS idx_vote_user ON votes(user_id);

-- =============================================
-- 4. VIEWS (Optional for H2)
-- =============================================

-- Recurring meetings view
CREATE VIEW IF NOT EXISTS recurring_meetings_view AS
SELECT
    m.id,
    m.title,
    m.start_date,
    m.recurrence_pattern,
    m.recurrence_end_date,
    m.is_template,
    u.email as organizer_email,
    COUNT(DISTINCT mp.id) as participant_count
FROM meetings m
JOIN users u ON m.organizer_id = u.id
LEFT JOIN meeting_participants mp ON m.id = mp.meeting_id AND mp.status = 'CONFIRMED'
WHERE m.is_recurring = TRUE
GROUP BY m.id, m.title, m.start_date, m.recurrence_pattern, m.recurrence_end_date, m.is_template, u.email;

-- Meeting templates view
CREATE VIEW IF NOT EXISTS meeting_templates_view AS
SELECT
    m.id,
    m.title,
    m.description,
    m.type,
    m.visibility,
    u.email as created_by_email,
    COUNT(DISTINCT mc.category_id) as category_count,
    GROUP_CONCAT(DISTINCT mt.tag) as tags
FROM meetings m
JOIN users u ON m.organizer_id = u.id
LEFT JOIN meeting_categories mc ON m.id = mc.meeting_id
LEFT JOIN meeting_tags mt ON m.id = mt.meeting_id
WHERE m.is_template = TRUE
GROUP BY m.id, m.title, m.description, m.type, m.visibility, u.email;



---- =============================================
---- MeetHub H2 Database Schema Script
---- For testing with Spring Boot Data JPA
---- =============================================
--
---- 1. CREATE SCHEMA (H2 doesn't support CREATE DATABASE in embedded mode)
--CREATE SCHEMA IF NOT EXISTS meethub_schema;
--
---- Set schema
--SET SCHEMA meethub_schema;
--
---- =============================================
---- 2. TABLES
---- =============================================
--
---- Users table
--CREATE TABLE IF NOT EXISTS users (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    email VARCHAR(255) UNIQUE NOT NULL,
--    password VARCHAR(255) NOT NULL,
--    first_name VARCHAR(100) NOT NULL,
--    last_name VARCHAR(100) NOT NULL,
--    role VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
--    phone_number VARCHAR(20),
--    enabled BOOLEAN NOT NULL DEFAULT TRUE,
--    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
--    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
--    account_locked_until TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    email_notifications_enabled BOOLEAN DEFAULT TRUE,
--    push_notifications_enabled BOOLEAN DEFAULT TRUE,
--    sms_notifications_enabled BOOLEAN DEFAULT FALSE,
--    digest_enabled BOOLEAN DEFAULT TRUE,
--    digest_frequency VARCHAR(20) DEFAULT 'DAILY',
--    timezone VARCHAR(50) DEFAULT 'Europe/Warsaw',
--    language VARCHAR(10) DEFAULT 'pl'
--);
--
---- User preferences table
--CREATE TABLE IF NOT EXISTS user_preferences (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    user_id BIGINT NOT NULL,
--    preference_key VARCHAR(100) NOT NULL,
--    preference_value VARCHAR(500),
--    privacy_level VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Locations table
--CREATE TABLE IF NOT EXISTS locations (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(200) NOT NULL,
--    address TEXT,
--    city VARCHAR(100),
--    country VARCHAR(100),
--    latitude DECIMAL(10, 6),
--    longitude DECIMAL(10, 6),
--    type VARCHAR(20) NOT NULL,
--    virtual_meeting_url VARCHAR(500),
--    access_code VARCHAR(50),
--    driving_instructions TEXT,
--    timezone VARCHAR(50)
--);
--
---- Meetings table
--CREATE TABLE IF NOT EXISTS meetings (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(200) NOT NULL,
--    description TEXT,
--    agenda TEXT,
--    type VARCHAR(20) NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
--    visibility VARCHAR(20) NOT NULL,
--    start_date TIMESTAMP NOT NULL,
--    end_date TIMESTAMP NOT NULL,
--    max_participants INTEGER,
--    organizer_id BIGINT NOT NULL,
--    location_id BIGINT,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    is_recurring BOOLEAN DEFAULT FALSE,
--    recurrence_pattern VARCHAR(100),
--    recurrence_end_date TIMESTAMP,
--    recurrence_exceptions VARCHAR(4000),
--    is_template BOOLEAN DEFAULT FALSE,
--    original_meeting_id BIGINT,
--    workflow_stage VARCHAR(50) DEFAULT 'DRAFT',
--    metadata VARCHAR(4000),
--    FOREIGN KEY (organizer_id) REFERENCES users(id),
--    FOREIGN KEY (location_id) REFERENCES locations(id),
--    FOREIGN KEY (original_meeting_id) REFERENCES meetings(id)
--);
--
---- Meeting tags table
--CREATE TABLE IF NOT EXISTS meeting_tags (
--    meeting_id BIGINT NOT NULL,
--    tag VARCHAR(100) NOT NULL,
--    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    added_by BIGINT,
--    PRIMARY KEY (meeting_id, tag),
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (added_by) REFERENCES users(id)
--);
--
---- Meeting participants table
--CREATE TABLE IF NOT EXISTS meeting_participants (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'INVITED',
--    permission_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANT',
--    comment TEXT,
--    invitation_token VARCHAR(100) UNIQUE,
--    token_expires_at TIMESTAMP,
--    response_date TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    join_method VARCHAR(50),
--    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
--    feedback TEXT,
--    attendance_duration_minutes INTEGER,
--    attendance_confirmed_at TIMESTAMP,
--    attendance_token_used VARCHAR(255),
--    UNIQUE (meeting_id, user_id),
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id)
--);
--
---- Participant status history table
--CREATE TABLE IF NOT EXISTS participant_status_history (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    participant_id BIGINT NOT NULL,
--    old_status VARCHAR(20),
--    new_status VARCHAR(20) NOT NULL,
--    comment TEXT,
--    changed_by_user_id BIGINT,
--    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (participant_id) REFERENCES meeting_participants(id) ON DELETE CASCADE,
--    FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
--);
--
---- Waitlist entries table
--CREATE TABLE IF NOT EXISTS waitlist_entries (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    position INTEGER NOT NULL,
--    auto_promote BOOLEAN NOT NULL DEFAULT TRUE,
--    notified_at TIMESTAMP,
--    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    UNIQUE (meeting_id, user_id),
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id)
--);
--
---- User groups table
--CREATE TABLE IF NOT EXISTS user_groups (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(200) NOT NULL UNIQUE,
--    description TEXT,
--    created_by BIGINT NOT NULL,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (created_by) REFERENCES users(id)
--);
--
---- User group members table
--CREATE TABLE IF NOT EXISTS user_group_members (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    group_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
--    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    UNIQUE (group_id, user_id),
--    FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id)
--);
--
---- Meeting resources table
--CREATE TABLE IF NOT EXISTS meeting_resources (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    filename VARCHAR(255) NOT NULL,
--    original_filename VARCHAR(255) NOT NULL,
--    file_path VARCHAR(500) NOT NULL,
--    file_size BIGINT,
--    mime_type VARCHAR(100),
--    resource_type VARCHAR(50) NOT NULL,
--    version INTEGER NOT NULL DEFAULT 1,
--    is_current BOOLEAN NOT NULL DEFAULT TRUE,
--    uploaded_by BIGINT,
--    access_level VARCHAR(20) NOT NULL DEFAULT 'PARTICIPANTS',
--    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    download_count INTEGER NOT NULL DEFAULT 0,
--    description TEXT,
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (uploaded_by) REFERENCES users(id)
--);
--
---- Resource tags table
--CREATE TABLE IF NOT EXISTS resource_tags (
--    resource_id BIGINT NOT NULL,
--    tag VARCHAR(100) NOT NULL,
--    PRIMARY KEY (resource_id, tag),
--    FOREIGN KEY (resource_id) REFERENCES meeting_resources(id) ON DELETE CASCADE
--);
--
---- Meeting tasks table
--CREATE TABLE IF NOT EXISTS meeting_tasks (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    title VARCHAR(200) NOT NULL,
--    description TEXT,
--    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
--    assigned_to BIGINT,
--    due_date TIMESTAMP,
--    completed_at TIMESTAMP,
--    progress_percentage INTEGER NOT NULL DEFAULT 0,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (assigned_to) REFERENCES users(id)
--);
--
---- Notifications table
--CREATE TABLE IF NOT EXISTS notifications (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    user_id BIGINT NOT NULL,
--    title VARCHAR(200) NOT NULL,
--    message TEXT,
--    type VARCHAR(20) NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
--    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL',
--    reference_id BIGINT,
--    reference_type VARCHAR(50),
--    sent_at TIMESTAMP,
--    read_at TIMESTAMP,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    template_key VARCHAR(100),
--    scheduled_for TIMESTAMP,
--    delivered_at TIMESTAMP,
--    retry_count INTEGER DEFAULT 0,
--    error_message TEXT,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Email templates table
--CREATE TABLE IF NOT EXISTS email_templates (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    template_key VARCHAR(100) UNIQUE NOT NULL,
--    subject VARCHAR(500) NOT NULL,
--    body_template TEXT NOT NULL,
--    language VARCHAR(10) NOT NULL DEFAULT 'pl',
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    name VARCHAR(200),
--    category VARCHAR(100),
--    description TEXT,
--    variables_help TEXT,
--    is_active BOOLEAN DEFAULT TRUE,
--    version INTEGER DEFAULT 1,
--    channel VARCHAR(50),
--    available_variables TEXT
--);
--
---- Tasks table
--CREATE TABLE IF NOT EXISTS tasks (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(255) NOT NULL,
--    description TEXT,
--    status VARCHAR(50) NOT NULL DEFAULT 'TODO',
--    deadline TIMESTAMP,
--    meeting_id BIGINT NOT NULL,
--    created_by BIGINT NOT NULL,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    allow_self_assignment BOOLEAN,
--    allowed_file_types TEXT DEFAULT 'pdf,doc,docx,jpg,png',
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Task assignments table
--CREATE TABLE IF NOT EXISTS task_assignments (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    status VARCHAR(50) NOT NULL DEFAULT 'ASSIGNED',
--    comment TEXT,
--    completed_at TIMESTAMP,
--    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    task_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    UNIQUE(task_id, user_id),
--    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Task files table
--CREATE TABLE IF NOT EXISTS task_files (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    filename VARCHAR(255) NOT NULL,
--    original_filename VARCHAR(255) NOT NULL,
--    file_path TEXT NOT NULL,
--    file_size BIGINT,
--    content_type VARCHAR(100),
--    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    assignment_id BIGINT NOT NULL,
--    FOREIGN KEY (assignment_id) REFERENCES task_assignments(id) ON DELETE CASCADE
--);
--
---- Feedback table
--CREATE TABLE IF NOT EXISTS feedbacks (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
--    comment TEXT,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    UNIQUE(meeting_id, user_id),
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Meeting statistics table
--CREATE TABLE meeting_statistics (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL UNIQUE,
--
--    -- Podstawowe metryki
--    total_participants INTEGER NOT NULL DEFAULT 0,
--    attended_participants INTEGER NOT NULL DEFAULT 0,
--    confirmed_participants INTEGER DEFAULT 0,
--    declined_participants INTEGER DEFAULT 0,
--    pending_participants INTEGER DEFAULT 0,
--
--    -- Frekwencja
--    attendance_rate DECIMAL(5,2),
--    confirmation_rate DECIMAL(5,2),
--
--    -- Czasy odpowiedzi
--    avg_response_time_minutes DECIMAL(10,2),
--    min_response_time_minutes DECIMAL(10,2),
--    max_response_time_minutes DECIMAL(10,2),
--
--    -- Czas trwania
--    avg_join_delay_minutes DECIMAL(10,2),
--    avg_participation_duration_minutes DECIMAL(10,2),
--    total_meeting_duration_minutes INTEGER,
--
--    -- Statystyki uczestnictwa
--    max_concurrent_participants INTEGER,
--    current_participants INTEGER DEFAULT 0,
--    peak_participants_today INTEGER DEFAULT 0,
--
--    -- Feedback
--    average_rating DECIMAL(3,2),
--    feedback_count INTEGER DEFAULT 0,
--    positive_feedback_count INTEGER DEFAULT 0,
--    negative_feedback_count INTEGER DEFAULT 0,
--
--    -- Koszty
--    total_cost DECIMAL(15,2),
--    cost_per_participant DECIMAL(10,2),
--
--    -- Statusy
--    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
--    is_finalized BOOLEAN NOT NULL DEFAULT FALSE,
--    data_quality_score DECIMAL(3,2),
--
--    -- Timestamps
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    generated_at TIMESTAMP NOT NULL,
--    last_calculated_at TIMESTAMP,
--    valid_until TIMESTAMP,
--
--    -- JSON metryki (H2 używa VARCHAR dla JSON)
--    additional_metrics VARCHAR(4000),
--
--    -- Wersja
--    version INTEGER DEFAULT 0,
--
--    -- Klucze obce
--    CONSTRAINT fk_meeting_statistics_meeting
--        FOREIGN KEY (meeting_id)
--        REFERENCES meetings(id) ON DELETE CASCADE,
--
--    -- Constraints
--    CONSTRAINT chk_attendance_rate_range
--        CHECK (attendance_rate >= 0 AND attendance_rate <= 100),
--    CONSTRAINT chk_confirmation_rate_range
--        CHECK (confirmation_rate >= 0 AND confirmation_rate <= 100),
--    CONSTRAINT chk_average_rating_range
--        CHECK (average_rating >= 0 AND average_rating <= 5)
--);
--
---- Meeting votings table
--CREATE TABLE IF NOT EXISTS meeting_votings (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    title VARCHAR(200) NOT NULL,
--    description TEXT,
--    type VARCHAR(20) NOT NULL,
--    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
--    max_choices INTEGER,
--    allow_suggestions BOOLEAN DEFAULT FALSE,
--    deadline_date TIMESTAMP,
--    auto_close BOOLEAN DEFAULT FALSE,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE
--);
--
---- Voting options table
--CREATE TABLE IF NOT EXISTS voting_options (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    voting_id BIGINT NOT NULL,
--    option_date TIMESTAMP NOT NULL,
--    option_duration_minutes INTEGER,
--    is_suggested BOOLEAN DEFAULT FALSE,
--    suggested_by BIGINT,
--    FOREIGN KEY (voting_id) REFERENCES meeting_votings(id) ON DELETE CASCADE,
--    FOREIGN KEY (suggested_by) REFERENCES users(id)
--);
--
---- Votes table
--CREATE TABLE IF NOT EXISTS votes (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    voting_id BIGINT NOT NULL,
--    option_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    vote_weight INTEGER DEFAULT 1,
--    preference_order INTEGER,
--    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    CONSTRAINT unique_user_voting_option UNIQUE (user_id, voting_id, option_id),
--    FOREIGN KEY (voting_id) REFERENCES meeting_votings(id) ON DELETE CASCADE,
--    FOREIGN KEY (option_id) REFERENCES voting_options(id) ON DELETE CASCADE,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Categories table
--CREATE TABLE IF NOT EXISTS categories (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(100) NOT NULL,
--    description VARCHAR(500),
--    color_code VARCHAR(7) DEFAULT '#3498db',
--    created_by BIGINT NOT NULL,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (created_by) REFERENCES users(id)
--);
--
---- Meeting categories table
--CREATE TABLE IF NOT EXISTS meeting_categories (
--    meeting_id BIGINT NOT NULL,
--    category_id BIGINT NOT NULL,
--    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    PRIMARY KEY (meeting_id, category_id),
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
--);
--
---- Meeting status changes table
--CREATE TABLE IF NOT EXISTS meeting_status_changes (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    meeting_id BIGINT NOT NULL,
--    old_status VARCHAR(50),
--    new_status VARCHAR(50) NOT NULL,
--    changed_by_user_id BIGINT,
--    reason VARCHAR(500),
--    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
--    FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
--);
--
---- Attendance tokens table
--CREATE TABLE IF NOT EXISTS attendance_tokens (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    token VARCHAR(255) NOT NULL UNIQUE,
--    user_id BIGINT NOT NULL,
--    meeting_id BIGINT NOT NULL,
--    expires_at TIMESTAMP NOT NULL,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    used_at TIMESTAMP,
--    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
--    FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE
--);
--
---- User notification channels table
--CREATE TABLE IF NOT EXISTS user_notification_channels (
--    user_id BIGINT NOT NULL,
--    channel VARCHAR(20) NOT NULL,
--    PRIMARY KEY (user_id, channel),
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- Notification variables table
--CREATE TABLE IF NOT EXISTS notification_variables (
--    notification_id BIGINT NOT NULL,
--    variable_key VARCHAR(100) NOT NULL,
--    variable_value TEXT,
--    PRIMARY KEY (notification_id, variable_key),
--    FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE
--);
--
---- Notification schedules table
--CREATE TABLE IF NOT EXISTS notification_schedules (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    user_id BIGINT NOT NULL,
--    schedule_type VARCHAR(50) NOT NULL,
--    trigger_time VARCHAR(20),
--    enabled BOOLEAN NOT NULL DEFAULT TRUE,
--    custom_settings TEXT,
--    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
--);
--
---- =============================================
---- 3. INDEXES (Basic indexes for H2)
---- =============================================
--
---- Users indexes
--CREATE INDEX IF NOT EXISTS idx_user_email ON users(email);
--CREATE INDEX IF NOT EXISTS idx_user_role ON users(role);
--CREATE INDEX IF NOT EXISTS idx_user_created ON users(created_at);
--
---- Meetings indexes
--CREATE INDEX IF NOT EXISTS idx_meeting_organizer ON meetings(organizer_id);
--CREATE INDEX IF NOT EXISTS idx_meeting_status ON meetings(status);
--CREATE INDEX IF NOT EXISTS idx_meeting_start_date ON meetings(start_date);
--CREATE INDEX IF NOT EXISTS idx_meeting_end_date ON meetings(end_date);
--
---- Meeting participants indexes
--CREATE INDEX IF NOT EXISTS idx_participant_meeting ON meeting_participants(meeting_id);
--CREATE INDEX IF NOT EXISTS idx_participant_user ON meeting_participants(user_id);
--CREATE INDEX IF NOT EXISTS idx_participant_status ON meeting_participants(status);
--
---- Notifications indexes
--CREATE INDEX IF NOT EXISTS idx_notification_user ON notifications(user_id);
--CREATE INDEX IF NOT EXISTS idx_notification_status ON notifications(status);
--
---- Voting indexes
--CREATE INDEX IF NOT EXISTS idx_voting_meeting ON meeting_votings(meeting_id);
--CREATE INDEX IF NOT EXISTS idx_vote_user ON votes(user_id);
--
---- =============================================
---- 4. VIEWS (Optional for H2)
---- =============================================
--
---- Recurring meetings view
--CREATE VIEW IF NOT EXISTS recurring_meetings_view AS
--SELECT
--    m.id,
--    m.title,
--    m.start_date,
--    m.recurrence_pattern,
--    m.recurrence_end_date,
--    m.is_template,
--    u.email as organizer_email,
--    COUNT(DISTINCT mp.id) as participant_count
--FROM meetings m
--JOIN users u ON m.organizer_id = u.id
--LEFT JOIN meeting_participants mp ON m.id = mp.meeting_id AND mp.status = 'CONFIRMED'
--WHERE m.is_recurring = TRUE
--GROUP BY m.id, m.title, m.start_date, m.recurrence_pattern, m.recurrence_end_date, m.is_template, u.email;
--
---- Meeting templates view
--CREATE VIEW IF NOT EXISTS meeting_templates_view AS
--SELECT
--    m.id,
--    m.title,
--    m.description,
--    m.type,
--    m.visibility,
--    u.email as created_by_email,
--    COUNT(DISTINCT mc.category_id) as category_count,
--    GROUP_CONCAT(DISTINCT mt.tag) as tags
--FROM meetings m
--JOIN users u ON m.organizer_id = u.id
--LEFT JOIN meeting_categories mc ON m.id = mc.meeting_id
--LEFT JOIN meeting_tags mt ON m.id = mt.meeting_id
--WHERE m.is_template = TRUE
--GROUP BY m.id, m.title, m.description, m.type, m.visibility, u.email;
--
--
--
--
---- =============================================
---- 5. TEST DATA FOR JPA TESTS (Optional)
---- =============================================
----
------ Insert minimal test data for JPA repository tests
----INSERT INTO users (email, password, first_name, last_name, role, enabled) VALUES
----('test.admin@example.com', '$2a$10$k9bUAugra.AHtbPWKwdcxu9v5a2YC/6D/msdYhXQKNnm8eTw.g4Uy', 'Admin', 'Test', 'ADMIN', true),
----('test.organizer@example.com', '$2a$10$k9bUAugra.AHtbPWKwdcxu9v5a2YC/6D/msdYhXQKNnm8eTw.g4Uy', 'Organizer', 'Test', 'ORGANIZER', true),
----('test.user@example.com', '$2a$10$k9bUAugra.AHtbPWKwdcxu9v5a2YC/6D/msdYhXQKNnm8eTw.g4Uy', 'User', 'Test', 'PARTICIPANT', true)
----ON DUPLICATE KEY UPDATE email = email;
----
------ Insert test location
----INSERT INTO locations (name, type, timezone) VALUES
----('Test Conference Room', 'PHYSICAL', 'Europe/Warsaw')
----ON DUPLICATE KEY UPDATE name = name;
----
------ Insert test meeting
----INSERT INTO meetings (title, description, type, status, visibility, start_date, end_date, organizer_id) VALUES
----('Test Meeting', 'Test Description', 'PHYSICAL', 'PLANNED', 'PUBLIC',
---- CURRENT_TIMESTAMP + INTERVAL '1 DAY',
---- CURRENT_TIMESTAMP + INTERVAL '1 DAY' + INTERVAL '2 HOUR',
---- (SELECT id FROM users WHERE email = 'test.organizer@example.com'))
----ON DUPLICATE KEY UPDATE title = title;